SELECT
  P.PRODUCT_NUMBER AS KIT_PRODUCT_NUMBER,
  PS.SERIAL_NUMBER AS KIT_SERIAL_NUMBER,
  P.ID AS KIT_PRODUCT_ID,
  PS.ID AS KIT_SERIAL_ID,
  S.ID AS KIT_STOCK_ID
FROM
  SMS_WRITE.STOCK S
  LEFT JOIN SMS_WRITE.PRODUCT P ON S.PRODUCT_ID = P.ID
  LEFT JOIN SMS_WRITE.PRODUCT_SERIAL PS ON S.SERIAL_ID = PS.ID
WHERE
  P.PRODUCT_NUMBER = '{}'
  AND PS.SERIAL_NUMBER IN ({})