WITH S0 AS (
    SELECT
      KIT_PRODUCT_NUMBER,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'STOCK_AVAILABLE'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS STOCK_AVAILABLE,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'COMPLETE_NEW_KIT_BUILD'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS COMPLETE_NEW_KIT_BUILD,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'NO_STOCK_AVAILABLE'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS NO_STOCK_AVAILABLE,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'PICK_SHORTAGE'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS PICK_SHORTAGE,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'COMPLETE_REPLENISHMENTS'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS COMPLETE_REPLENISHMENTS,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'COMPLETE_PUTAWAY'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS COMPLETE_PUTAWAY,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'MANUEL_INVESTIGATION_REQUIRED'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS MANUEL_INVESTIGATION_REQUIRED,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'EMPTY'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS EMPTY,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'CORPORATE_HOLD'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS CORPORATE_HOLD,
      (CASE WHEN POTENTIAL_ACTION_ON_KIT = 'NO_ACTION_REQUIRED'
        THEN KIT_SERIAL_NUMBER
       ELSE NULL END) AS NO_ACTION_REQUIRED
    FROM
      DOARNI.NEW_KIT_PROGRESS_TRACKER
    GROUP BY
      KIT_PRODUCT_NUMBER,
      KIT_SERIAL_NUMBER,
      POTENTIAL_ACTION_ON_KIT
    ORDER BY
      KIT_PRODUCT_NUMBER,
      KIT_SERIAL_NUMBER ASC
),
    S1 AS (
      SELECT
        KIT_PRODUCT_NUMBER,
        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(STOCK_AVAILABLE), NULL), ', ')         STOCK_AVAILABLE,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(STOCK_AVAILABLE), NULL), 1)               COUNT_OF_STOCK_AVAILABLE,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(COMPLETE_NEW_KIT_BUILD), NULL), ', ')  COMPLETE_NEW_KIT_BUILD,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(COMPLETE_NEW_KIT_BUILD), NULL), 1)        COUNT_OF_COMPLETE_NEW_KIT_BUILD,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(NO_STOCK_AVAILABLE), NULL), ', ')      NO_STOCK_AVAILABLE,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(NO_STOCK_AVAILABLE), NULL), 1)            COUNT_OF_NO_STOCK_AVAILABLE,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(PICK_SHORTAGE), NULL), ', ')           PICK_SHORTAGE,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(PICK_SHORTAGE), NULL), 1)                 COUNT_OF_PICK_SHORTAGE,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(COMPLETE_REPLENISHMENTS), NULL), ', ') COMPLETE_REPLENISHMENTS,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(COMPLETE_REPLENISHMENTS), NULL), 1)       COUNT_OF_COMPLETE_REPLENISHMENTS,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(COMPLETE_PUTAWAY), NULL), ', ')        COMPLETE_PUTAWAY,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(COMPLETE_PUTAWAY), NULL), 1)              COUNT_OF_COMPLETE_PUTAWAY,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(MANUEL_INVESTIGATION_REQUIRED), NULL),
                        ', ')                                                         MANUEL_INVESTIGATION_REQUIRED,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(MANUEL_INVESTIGATION_REQUIRED), NULL),
                     1)                                                               COUNT_OF_MANUEL_INVESTIGATION_REQUIRED,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(EMPTY), NULL), ', ')                   EMPTY,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(EMPTY), NULL), 1)                         COUNT_OF_EMPTY,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(CORPORATE_HOLD), NULL), ', ')          CORPORATE_HOLD,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(CORPORATE_HOLD), NULL), 1)                COUNT_OF_CORPORATE_HOLD,

        ARRAY_TO_STRING(ARRAY_REMOVE(ARRAY_AGG(NO_ACTION_REQUIRED), NULL), ', ')      NO_ACTION_REQUIRED,
        ARRAY_LENGTH(ARRAY_REMOVE(ARRAY_AGG(NO_ACTION_REQUIRED), NULL), 1)            COUNT_OF_NO_ACTION_REQUIRED

      FROM
        S0
      GROUP BY
        KIT_PRODUCT_NUMBER
  )
SELECT
  KIT_PRODUCT_NUMBER,

  COUNT_OF_NO_ACTION_REQUIRED +
  COUNT_OF_CORPORATE_HOLD +
  COUNT_OF_EMPTY +
  COUNT_OF_MANUEL_INVESTIGATION_REQUIRED +
  COUNT_OF_COMPLETE_PUTAWAY +
  COUNT_OF_PICK_SHORTAGE +
  COUNT_OF_NO_STOCK_AVAILABLE +
  COUNT_OF_COMPLETE_NEW_KIT_BUILD +
  COUNT_OF_COMPLETE_REPLENISHMENTS +
  COUNT_OF_STOCK_AVAILABLE AS TOTAL_COUNT_OR_SERIALS,

  CASE WHEN STOCK_AVAILABLE = '{}'
    THEN NULL
  ELSE STOCK_AVAILABLE END                            AS STOCK_AVAILABLE,
  COALESCE(COUNT_OF_STOCK_AVAILABLE, 0)               AS COUNT_OF_STOCK_AVAILABLE,

  CASE WHEN COMPLETE_NEW_KIT_BUILD = '{}'
    THEN NULL
  ELSE COMPLETE_NEW_KIT_BUILD END                     AS COMPLETE_NEW_KIT_BUILD,
  COALESCE(COUNT_OF_COMPLETE_NEW_KIT_BUILD, 0)        AS COUNT_OF_COMPLETE_NEW_KIT_BUILD,

  CASE WHEN NO_STOCK_AVAILABLE = '{}'
    THEN NULL
  ELSE NO_STOCK_AVAILABLE END                         AS NO_STOCK_AVAILABLE,
  COALESCE(COUNT_OF_NO_STOCK_AVAILABLE, 0)            AS COUNT_OF_NO_STOCK_AVAILABLE,

  CASE WHEN PICK_SHORTAGE = '{}'
    THEN NULL
  ELSE PICK_SHORTAGE END                              AS PICK_SHORTAGE,
  COALESCE(COUNT_OF_PICK_SHORTAGE, 0)                 AS COUNT_OF_PICK_SHORTAGE,

  CASE WHEN COMPLETE_REPLENISHMENTS = '{}'
    THEN NULL
  ELSE COMPLETE_REPLENISHMENTS END                    AS COMPLETE_REPLENISHMENTS,
  COALESCE(COUNT_OF_COMPLETE_REPLENISHMENTS, 0)       AS COUNT_OF_COMPLETE_REPLENISHMENTS,

  CASE WHEN COMPLETE_PUTAWAY = '{}'
    THEN NULL
  ELSE COMPLETE_PUTAWAY END                           AS COMPLETE_PUTAWAY,
  COALESCE(COUNT_OF_COMPLETE_PUTAWAY, 0)              AS COUNT_OF_COMPLETE_PUTAWAY,

  CASE WHEN MANUEL_INVESTIGATION_REQUIRED = '{}'
    THEN NULL
  ELSE MANUEL_INVESTIGATION_REQUIRED END              AS MANUEL_INVESTIGATION_REQUIRED,
  COALESCE(COUNT_OF_MANUEL_INVESTIGATION_REQUIRED, 0) AS COUNT_OF_MANUEL_INVESTIGATION_REQUIRED,

  CASE WHEN EMPTY = '{}'
    THEN NULL
  ELSE EMPTY END                                      AS EMPTY,
  COALESCE(COUNT_OF_EMPTY, 0)                         AS COUNT_OF_EMPTY,

  CASE WHEN CORPORATE_HOLD = '{}'
    THEN NULL
  ELSE CORPORATE_HOLD END                             AS CORPORATE_HOLD,
  COALESCE(COUNT_OF_CORPORATE_HOLD, 0)                AS COUNT_OF_CORPORATE_HOLD,

  CASE WHEN NO_ACTION_REQUIRED = '{}'
    THEN NULL
  ELSE NO_ACTION_REQUIRED END                         AS NO_ACTION_REQUIRED,
  COALESCE(COUNT_OF_NO_ACTION_REQUIRED, 0)            AS COUNT_OF_NO_ACTION_REQUIRED

FROM
  S1